version: "3.5"
services:
  nethermind:
    build:
      context: .
      args:
        UPSTREAM_VERSION: 1.13.3
    image: "nethermind.public.dappnode.eth:1.0.9"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "data:/data"
    environment:
      MODE: normal
      NETHERMIND_CONFIG: mainnet
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      EXTRA_OPTS: null
    ports:
      - "30305:30305/udp"
      - "30305:30305/tcp"
volumes:
  data: {}
