version: "3.4"
services:
  nethermind.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 1.12.6
    image: "nethermind.dnp.dappnode.eth.nethermind.public.dappnode.eth:1.0.9"
    restart: unless-stopped
    volumes:
      - "data:/data"
    environment:
      NETHERMIND_CONFIG: mainnet
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      EXTRA_OPTS: null
    ports:
      - 30303/tcp
      - 30303/udp
      - 30304/tcp
      - 30304/udp
volumes:
  data: {}
